import type {
  JourneyPlan,
  RecentJourney,
  FavouriteDestination,
  TravelStat,
} from "@/types/journey";

// ─── MOCK JOURNEY PLAN ────────────────────────────────────────────────────────
// Demo route: London King's Cross → Tower Bridge

export const mockJourneyPlan: JourneyPlan = {
  id: "journey-demo-001",
  from: "King's Cross St. Pancras",
  to: "Tower Bridge",
  date: "2025-08-15",
  travellers: 2,
  budget: 50,
  preferences: ["tourist", "family"],

  routes: [
    {
      id: "route-fastest",
      name: "Metro Express",
      tag: "Fastest",
      tagColor: "cyan",
      totalTime: 28,
      walkingTime: 10,
      totalFare: 5.4,
      transfers: 1,
      carbonKg: 0.4,
      overallScore: 91,
      isRecommended: true,
      segments: [
        {
          mode: "walk",
          label: "Walk to Station",
          from: "King's Cross",
          to: "King's Cross Underground",
          duration: 3,
          distance: 250,
          fare: 0,
          coordinates: [
            [51.5309, -0.1233],
            [51.5306, -0.1239],
          ],
        },
        {
          mode: "metro",
          label: "Circle Line",
          from: "King's Cross St. Pancras",
          to: "Monument",
          duration: 18,
          distance: 6200,
          fare: 2.7,
          line: "Circle Line",
          stops: 7,
          coordinates: [
            [51.5306, -0.1239],
            [51.5074, -0.0878],
          ],
        },
        {
          mode: "walk",
          label: "Walk to Tower Bridge",
          from: "Monument Station",
          to: "Tower Bridge",
          duration: 7,
          distance: 600,
          fare: 0,
          coordinates: [
            [51.5074, -0.0878],
            [51.5055, -0.0754],
          ],
        },
      ],
    },
    {
      id: "route-eco",
      name: "Eco Ride",
      tag: "Eco Friendly",
      tagColor: "green",
      totalTime: 42,
      walkingTime: 22,
      totalFare: 2.7,
      transfers: 0,
      carbonKg: 0.1,
      overallScore: 85,
      isRecommended: false,
      segments: [
        {
          mode: "bus",
          label: "Bus 17",
          from: "King's Cross",
          to: "Aldgate",
          duration: 30,
          distance: 8100,
          fare: 1.75,
          line: "Bus 17",
          coordinates: [
            [51.5309, -0.1233],
            [51.5143, -0.0773],
          ],
        },
        {
          mode: "walk",
          label: "Walk to Tower Bridge",
          from: "Aldgate Bus Stop",
          to: "Tower Bridge",
          duration: 12,
          distance: 1100,
          fare: 0,
          coordinates: [
            [51.5143, -0.0773],
            [51.5055, -0.0754],
          ],
        },
      ],
    },
    {
      id: "route-comfort",
      name: "Taxi Direct",
      tag: "Most Comfortable",
      tagColor: "purple",
      totalTime: 22,
      walkingTime: 3,
      totalFare: 18.5,
      transfers: 0,
      carbonKg: 2.1,
      overallScore: 74,
      isRecommended: false,
      segments: [
        {
          mode: "taxi",
          label: "Black Cab",
          from: "King's Cross",
          to: "Tower Bridge",
          duration: 22,
          distance: 7900,
          fare: 18.5,
          coordinates: [
            [51.5309, -0.1233],
            [51.5055, -0.0754],
          ],
        },
      ],
    },
  ],

  weather: {
    location: "Tower Bridge, London",
    current: {
      temp: 19,
      feelsLike: 17,
      condition: "Partly Cloudy",
      icon: "⛅",
      windSpeed: 14,
      humidity: 68,
      uvIndex: 4,
      rainAlert: true,
      rainAlertMessage: "Rain expected after 3:00 PM. Carry an umbrella.",
    },
    forecast: [
      { day: "Today", high: 19, low: 14, condition: "Partly Cloudy", icon: "⛅", rainChance: 40 },
      { day: "Thu", high: 22, low: 16, condition: "Sunny", icon: "☀️", rainChance: 5 },
      { day: "Fri", high: 20, low: 15, condition: "Cloudy", icon: "🌥️", rainChance: 25 },
      { day: "Sat", high: 16, low: 12, condition: "Rainy", icon: "🌧️", rainChance: 85 },
      { day: "Sun", high: 18, low: 13, condition: "Showers", icon: "🌦️", rainChance: 60 },
    ],
    clothingSuggestion:
      "Light jacket recommended. Rain is possible in the afternoon — pack a compact umbrella. Comfortable walking shoes advised.",
  },

  foodStops: [
    {
      id: "food-001",
      name: "Café Rouge Monument",
      cuisine: "French",
      type: "cafe",
      rating: 4.3,
      priceRange: "££",
      estimatedCost: 18,
      distanceFromRoute: 120,
      openNow: true,
      address: "1 Fish Street Hill, London EC3R 6DB",
      highlights: ["Great views", "Vegetarian options", "Good coffee"],
      coordinate: [51.5076, -0.0861],
    },
    {
      id: "food-002",
      name: "The Anchor & Hope",
      cuisine: "British",
      type: "restaurant",
      rating: 4.6,
      priceRange: "££",
      estimatedCost: 25,
      distanceFromRoute: 200,
      openNow: true,
      address: "36 The Cut, London SE1 8LP",
      highlights: ["Award winning", "Seasonal menu", "Highly rated"],
      coordinate: [51.5032, -0.1046],
    },
    {
      id: "food-003",
      name: "Dishoom King's Cross",
      cuisine: "Indian",
      type: "restaurant",
      rating: 4.8,
      priceRange: "££",
      estimatedCost: 22,
      distanceFromRoute: 350,
      openNow: true,
      address: "5 Stable St, London N1C 4AB",
      highlights: ["Iconic Bombay cafe", "Must try bacon naan", "Legendary"],
      coordinate: [51.5362, -0.1246],
    },
    {
      id: "food-004",
      name: "Pret A Manger",
      cuisine: "Sandwiches & Salads",
      type: "cafe",
      rating: 4.1,
      priceRange: "£",
      estimatedCost: 8,
      distanceFromRoute: 50,
      openNow: true,
      address: "Monument Street, London EC3R 8AP",
      highlights: ["Quick grab & go", "Vegan options", "Budget friendly"],
      coordinate: [51.508, -0.086],
    },
    {
      id: "food-005",
      name: "Five Guys Strand",
      cuisine: "American Burgers",
      type: "fastfood",
      rating: 4.4,
      priceRange: "£",
      estimatedCost: 14,
      distanceFromRoute: 180,
      openNow: true,
      address: "1-3 The Strand, London WC2N 5HR",
      highlights: ["Customizable burgers", "Fresh cut fries", "Family friendly"],
      coordinate: [51.5083, -0.1217],
    },
  ],

  essentials: [
    {
      id: "ess-001",
      name: "London Bridge Hospital",
      type: "hospital",
      distance: 420,
      address: "27 Tooley St, London SE1 2PR",
      openNow: true,
      coordinate: [51.504, -0.0836],
    },
    {
      id: "ess-002",
      name: "Boots Pharmacy — Monument",
      type: "pharmacy",
      distance: 90,
      address: "4 Monument St, London EC3R 8DY",
      openNow: true,
      coordinate: [51.5077, -0.0863],
    },
    {
      id: "ess-003",
      name: "Barclays ATM — London Bridge",
      type: "atm",
      distance: 65,
      address: "London Bridge St, London SE1 9SG",
      openNow: true,
      coordinate: [51.5054, -0.0861],
    },
    {
      id: "ess-004",
      name: "Public Restrooms — Tooley St",
      type: "restroom",
      distance: 200,
      address: "Tooley Street, London SE1",
      openNow: true,
      coordinate: [51.504, -0.082],
    },
    {
      id: "ess-005",
      name: "BP Petrol Station — Borough High St",
      type: "fuel",
      distance: 750,
      address: "60 Borough High St, London SE1 1XF",
      openNow: true,
      coordinate: [51.502, -0.0915],
    },
    {
      id: "ess-006",
      name: "Lloyds Pharmacy — King's Cross",
      type: "pharmacy",
      distance: 180,
      address: "King's Cross Station, London N1C 4TB",
      openNow: true,
      coordinate: [51.5308, -0.1238],
    },
  ],

  attractions: [
    {
      id: "attr-001",
      name: "Tower Bridge",
      category: "Landmark",
      rating: 4.8,
      distance: 0,
      description:
        "Iconic Victorian bascule bridge over the Thames. Visit the glass walkway for breathtaking city views.",
      estimatedTime: 60,
      free: false,
      entryFee: 12.3,
      coordinate: [51.5055, -0.0754],
      emoji: "🌉",
    },
    {
      id: "attr-002",
      name: "Tower of London",
      category: "Historic Site",
      rating: 4.7,
      distance: 300,
      description:
        "900 years of history. See the Crown Jewels, medieval towers, and Beefeater guards.",
      estimatedTime: 120,
      free: false,
      entryFee: 29.9,
      coordinate: [51.5081, -0.0759],
      emoji: "🏰",
    },
    {
      id: "attr-003",
      name: "The Monument",
      category: "Historic Landmark",
      rating: 4.5,
      distance: 600,
      description:
        "Commemorate the Great Fire of London from the top of this 17th-century column.",
      estimatedTime: 30,
      free: false,
      entryFee: 6.0,
      coordinate: [51.5101, -0.0861],
      emoji: "🗽",
    },
    {
      id: "attr-004",
      name: "Borough Market",
      category: "Food & Culture",
      rating: 4.7,
      distance: 900,
      description:
        "London's most renowned food market. Over 100 food stalls offering artisan produce from around the world.",
      estimatedTime: 45,
      free: true,
      coordinate: [51.5054, -0.0905],
      emoji: "🛒",
    },
    {
      id: "attr-005",
      name: "HMS Belfast",
      category: "Museum",
      rating: 4.5,
      distance: 350,
      description:
        "Europe's last surviving big gun WWII warship, moored on the Thames. Fascinating for all ages.",
      estimatedTime: 90,
      free: false,
      entryFee: 28.5,
      coordinate: [51.5063, -0.0815],
      emoji: "🚢",
    },
  ],

  budget_breakdown: {
    transport: 10.8,
    food: 30,
    attractions: 42.2,
    miscellaneous: 10,
    total: 93,
    currency: "GBP",
    perPersonTotal: 46.5,
    travellers: 2,
  },

  carbon: {
    selectedRouteCO2: 0.4,
    alternatives: [
      { mode: "Private Car", co2: 3.2, label: "3.2 kg CO₂" },
      { mode: "Taxi / Uber", co2: 2.1, label: "2.1 kg CO₂" },
      { mode: "Bus", co2: 0.1, label: "0.1 kg CO₂" },
      { mode: "Metro (your route)", co2: 0.4, label: "0.4 kg CO₂" },
      { mode: "Cycling", co2: 0.0, label: "Zero CO₂" },
      { mode: "Walking", co2: 0.0, label: "Zero CO₂" },
    ],
    treesEquivalent: 0.04,
    savingVsCar: 2.8,
    greenTip:
      "Switching to the Bus route saves an additional 0.3 kg CO₂ on this trip. Over 50 similar journeys, that's 15 kg — equivalent to planting a tree!",
  },

  aiSuggestions: [
    {
      id: "ai-001",
      icon: "🌧️",
      category: "weather",
      message:
        "Rain is expected after 3:00 PM today. We recommend starting your journey before 2:00 PM or carrying a compact umbrella.",
      severity: "warning",
    },
    {
      id: "ai-002",
      icon: "💊",
      category: "health",
      message:
        "A Boots Pharmacy is located just 90 meters from Monument Station — your transfer point. Ideal for any last-minute travel essentials.",
      severity: "tip",
    },
    {
      id: "ai-003",
      icon: "🧑‍👩‍👧",
      category: "safety",
      message:
        "This route uses step-free access at all stations, making it suitable for families with prams and young children.",
      severity: "info",
    },
    {
      id: "ai-004",
      icon: "🥗",
      category: "food",
      message:
        "Dishoom King's Cross has a 4.8-star rating and is just 350 meters from your start point — perfect for a pre-journey breakfast.",
      severity: "tip",
    },
    {
      id: "ai-005",
      icon: "🌿",
      category: "eco",
      message:
        "Your chosen Metro route produces 87% fewer emissions than a private car for this journey. Great eco choice!",
      severity: "info",
    },
    {
      id: "ai-006",
      icon: "⏰",
      category: "time",
      message:
        "Avoid travelling during 8–9 AM and 5–6 PM peak hours. The Circle Line can get crowded — off-peak travel is 40% less congested.",
      severity: "warning",
    },
    {
      id: "ai-007",
      icon: "📸",
      category: "food",
      message:
        "Borough Market, just 900 meters from Tower Bridge, is open until 5 PM. A perfect post-destination detour for food lovers and photographers.",
      severity: "tip",
    },
  ],
};

// ─── DASHBOARD MOCK DATA ──────────────────────────────────────────────────────

export const mockRecentJourneys: RecentJourney[] = [
  {
    id: "rj-001",
    from: "King's Cross",
    to: "Tower Bridge",
    date: "2025-08-15",
    mode: "metro",
    cost: 5.4,
    duration: 28,
    co2: 0.4,
  },
  {
    id: "rj-002",
    from: "Heathrow Airport",
    to: "Paddington Station",
    date: "2025-08-12",
    mode: "train",
    cost: 12.5,
    duration: 20,
    co2: 0.3,
  },
  {
    id: "rj-003",
    from: "Victoria Station",
    to: "Brighton",
    date: "2025-08-10",
    mode: "train",
    cost: 18.0,
    duration: 55,
    co2: 1.2,
  },
  {
    id: "rj-004",
    from: "Canary Wharf",
    to: "Shoreditch High St",
    date: "2025-08-08",
    mode: "bus",
    cost: 1.75,
    duration: 22,
    co2: 0.08,
  },
  {
    id: "rj-005",
    from: "Oxford Circus",
    to: "Camden Town",
    date: "2025-08-06",
    mode: "metro",
    cost: 2.7,
    duration: 14,
    co2: 0.2,
  },
];

export const mockFavouriteDestinations: FavouriteDestination[] = [
  { id: "fav-001", name: "Tower Bridge", country: "London, UK", emoji: "🌉", lastVisited: "Aug 2025", totalVisits: 8 },
  { id: "fav-002", name: "Brighton Beach", country: "Brighton, UK", emoji: "🏖️", lastVisited: "Aug 2025", totalVisits: 3 },
  { id: "fav-003", name: "Borough Market", country: "London, UK", emoji: "🛒", lastVisited: "Jul 2025", totalVisits: 12 },
  { id: "fav-004", name: "Heathrow Airport", country: "London, UK", emoji: "✈️", lastVisited: "Aug 2025", totalVisits: 5 },
  { id: "fav-005", name: "Camden Town", country: "London, UK", emoji: "🎸", lastVisited: "Aug 2025", totalVisits: 7 },
  { id: "fav-006", name: "Canary Wharf", country: "London, UK", emoji: "🏙️", lastVisited: "Aug 2025", totalVisits: 15 },
];

export const mockTravelStats: TravelStat[] = [
  { label: "Total Journeys", value: "127", unit: "trips", icon: "🗺️", trend: "up" },
  { label: "Distance Travelled", value: "4,820", unit: "km", icon: "📍", trend: "up" },
  { label: "CO₂ Saved vs Car", value: "38.4", unit: "kg", icon: "🌿", trend: "up" },
  { label: "Money Saved", value: "£214", unit: "this year", icon: "💰", trend: "up" },
  { label: "Avg Journey Time", value: "31", unit: "min", icon: "⏱️", trend: "down" },
  { label: "Eco Routes Chosen", value: "73%", unit: "of trips", icon: "♻️", trend: "up" },
];

export const mockBudgetChartData = [
  { month: "Mar", spent: 42, saved: 18 },
  { month: "Apr", spent: 38, saved: 22 },
  { month: "May", spent: 55, saved: 10 },
  { month: "Jun", spent: 30, saved: 35 },
  { month: "Jul", spent: 47, saved: 28 },
  { month: "Aug", spent: 93, saved: 15 },
];

export const mockCarbonChartData = [
  { month: "Mar", co2: 4.2 },
  { month: "Apr", co2: 3.8 },
  { month: "May", co2: 5.5 },
  { month: "Jun", co2: 2.9 },
  { month: "Jul", co2: 3.4 },
  { month: "Aug", co2: 1.8 },
];

// ─── TRAVEL PREFERENCES CONFIG ────────────────────────────────────────────────

export const travelPreferences = [
  { id: "elderly", label: "Elderly Friendly", emoji: "👵", description: "Step-free access, elevators, no stairs" },
  { id: "family", label: "Family", emoji: "👨‍👩‍👧", description: "Pram friendly, family carriages" },
  { id: "baby", label: "Baby Friendly", emoji: "👶", description: "Quiet areas, baby change facilities" },
  { id: "wheelchair", label: "Wheelchair Accessible", emoji: "♿", description: "Fully accessible routes" },
  { id: "budget", label: "Budget Saver", emoji: "💰", description: "Lowest cost journey options" },
  { id: "fastest", label: "Fastest Route", emoji: "⚡", description: "Minimise travel time" },
  { id: "eco", label: "Eco Friendly", emoji: "🌿", description: "Lowest carbon footprint" },
  { id: "foodie", label: "Food Explorer", emoji: "🍽", description: "Route near top restaurants" },
  { id: "tourist", label: "Tourist Mode", emoji: "📸", description: "Pass key sights & attractions" },
  { id: "backpacker", label: "Backpacker", emoji: "🎒", description: "Ultra budget, flexible options" },
] as const;
